string = input('Введите первый и последний день недели на английском')
print(len(string))
print(string.upper())
print(string.lower())
print(string.replace('Monday', "Понедельник"))
print(string[0])
print(string[-1])
print()
string = input('Имя Пушкина')
print(string.encode(encoding='utf-8', errors='strict'))
print(string.capitalize())
print(string.casefold())
print()
string = input('Сколько лет было Пушкину на момент смерти?')
print(string.zfill(6))
print()
print('Всё!')
